### ISSUE TITLE
Email is not working.

### ISSUE THREAD

**Issue by SigurdVie** [LemmyNet/lemmy-ansible#105]
After updating the lemmy instance to 0.18.0 the emails won't work.

Whenever i try to press "forgot password" on my Lemmy instance, i get this error in the bottom right corner:
`SyntaxError: Unexpected end of JSON input` and `email_send_fail`

Is this a problem with ansible, or is this something i should make an issue for on the main Lemmy repo?

**Comment by Freeman8461** [comment]
I am seeing this too. 

Some steps I have taken was to pull the documentation on the postfix implementation here: https://github.com/wader/postfix-relay

Here are the additions to my postfix section in docker-compose.yml

`     - RSYSLOG_LOG_TO_FILE=yes
      - RSYSLOG_TIMESTAMP=yes
    volumes:
      - ./volumes/postfix:/var/log/
`

And I added logging to my postfix relay to dump to a logfile.

I am seeing output to that file.: 
`2023-06-24T22:17:20.951373+00:00 6d277825eac5 postfix/master[129]: terminating on signal 15
2023-06-24T23:27:04.292299+00:00 57981c5d6c98 postfix/master[129]: terminating on signal 15
2023-06-24T23:27:47.886834+00:00 57981c5d6c98 postfix/master[121]: daemon started -- version 3.4.23, configuration /etc/postfix
`
That said when i request a password reset - or fill out a form for a new account i see the following in the logstream

`lemmy_1     | 2023-06-24T23:37:31.836993Z  WARN lemmy_server::root_span_builder: email_send_failed: Connection error: failed to lookup address information: Name does not resolve
lemmy_1     |    0: lemmy_api::local_user::reset_password::perform
lemmy_1     |              at crates/api/src/local_user/reset_password.rs:15
lemmy_1     |    1: lemmy_server::root_span_builder::HTTP request
lemmy_1     |            with http.method=POST http.scheme="http" http.host=lemmy.pub http.target=/api/v3/user/password_reset otel.kind="server" request_id=1cafc0b9-ece5-4b9f-8b21-6ae0cadc2b6c
lemmy_1     |              at src/root_span_builder.rs:16
lemmy_1     | LemmyError { message: Some("email_send_failed"), inner: Connection error: failed to lookup address information: Name does not resolve
lemmy_1     | 
lemmy_1     | Caused by:
lemmy_1     |     failed to lookup address information: Name does not resolve, context: SpanTrace [{ target: "lemmy_api::local_user::reset_password", name: "perform", file: "crates/api/src/local_user/reset_password.rs", line: 15 }, { target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "http.method=POST http.scheme=\"http\" http.host=lemmy.pub http.target=/api/v3/user/password_reset otel.kind=\"server\" request_id=1cafc0b9-ece5-4b9f-8b21-6ae0cadc2b6c", file: "src/root_span_builder.rs", line: 16 }] }`

Note the logstream is an output of the lemmy container. No information is even sent to postfix.

That said the lemmy app container does have functioning DNS resolution. Heres a dump

`sudo docker exec -ti lemmypub_lemmy_1 /bin/sh
/ # nslookup
BusyBox v1.36.1 (2023-06-02 00:42:02 UTC) multi-call binary.

Usage: nslookup [-type=QUERY_TYPE] [-debug] HOST [DNS_SERVER]

Query DNS about HOST

QUERY_TYPE: soa,ns,a,aaaa,cname,mx,txt,ptr,srv,any
/ # nslookup gmail.com
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	gmail.com
Address: 2607:f8b0:4000:80a::2005

Non-authoritative answer:
Name:	gmail.com
Address: 142.251.33.5
`

**Comment by Freeman8461** [comment]
@SigurdVie - Got it working. Some discussion here: https://r.rosettast0ned.com/comment/69757

PR is in from him as well here: https://github.com/LemmyNet/lemmy-ansible/pull/102

My config also has some extra options to output to a file, from the docker container used by lemmy here: https://github.com/wader/postfix-relay

**Comment by db0** [comment]
I had the same. I fixed it by adding both networks to the postfix container

**Comment by XIRGO** [comment]
I made a pull request here https://github.com/LemmyNet/lemmy-ansible/pull/99 about this

**Comment by ticoombs** [comment]
This should be closed now. 

Latest ansible code now has removed all networks.

#close

**Comment by dessalines** [comment]
Thanks @ticoombs ! Would you be interested in becoming a maintainer of this repo?

**Comment by ticoombs** [comment]
> interested in becoming another maintainer of this repo

Sure. I can help filter though some of these issues if you like. My own ansible code is what I would class as _average_ and I'm already pretty far away from this now. So it'll be nice to see if I could merge back upstream as well.

**Comment by dessalines** [comment]
Sweet, thx!
