### ISSUE TITLE
AnsibleUndefinedVariable: 'postgres_password' is undefined

### ISSUE THREAD

**Issue by sanatsathaye** [LemmyNet/lemmy-ansible#169]
Got this when running both `lemmy.yml` and `lemmy-almalinux.yml`

```
TASK [Add the config.hjson] 
/********************************************************************************************************************************
task path: /home/sanat/lemmy-ansible/lemmy-almalinux.yml:140
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'postgres_password' is undefined. 'postgres_password' is undefined
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'postgres_password' is undefined. 'postgres_password' is undefined"}
```

I believe this is happening because our `vars.yml` is inside `inventory/host_vars/{{ domain }}/` rather than `inventory/host_vars/` itself as per [documentation](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable).

I already have a fix for this in my local machine:

```  
vars_files:
    - inventory/host_vars/{{ domain }}/vars.yml
```

That said I'm not sure if there are plans to change anything around variable centralisation again, or if anyone else has a suggestion to solve this in a different way so creating an issue for discussion.

**Comment by sanatsathaye** [comment]
I'm not sure if the current setup will work on more... let's say exotic installs, like if someone decides to deploy a lemmy instance which is load balanced across servers. I mean I have no idea if the rest of the lemmy infrastructure can actually handle this setup but let's assume it can :D

I haven't tried this out much, but maybe instead of `host_vars` you can make use of `group_vars`? We have `lemmy` hardcoded as the group name so `inventory/group_vars/lemmy` can be created as part of the installation instructions and the vars moved there, with warnings in documentation to absolutely not touch that group name.

Not sure how that will affect the rest of the files already in host_vars though, that will need looking at. And using `group_vars` would mean all servers in that group will have the same config such as passwords which has its own pros and cons I suppose.

**Comment by RedKrieg** [comment]
I spent some time on this today and I believe there are some issues with the new vars.yml system for existing installs of lemmy-ansible.

1. The postgres password file is renamed from `passwords/postgres` to `passwords/postgres.psk` in a8c859da60d31281faa34d1de57049f728436121.  This was done to prevent ansible from trying to parse it as yaml, but it should be documented and the README should be updated accordingly (it currently still says users should use the `passwords/postgres` path when migrating).
2. Prior to 31631d2616de68f4398f976b6a569f68a02bdd9f user names were expected to be part of the host name in the `hosts` file, meaning that the built-in inventory vars system was looking in the wrong place (`user@domain` instead of just `domain`) for host_vars.

Obviously `ansible_user` is a better choice here, and moving more variables in to inventory is good, but existing users will expect that a `git pull` and a check of the [upgrading](https://github.com/LemmyNet/lemmy-ansible/blob/main/README.md#upgrading) docs is all they should need to do when upgrading.

For those seeing the error in the title, change your `hosts` file to use `ansible_user` instead of `user@` (see `examples/hosts`).  After that, rename `inventory/host_vars/<your_domain>/passwords/postgres` to `inventory/host_vars/<your_domain>/passwords/postgres.psk`.

**Comment by codyro** [comment]
The migrations documentation could be improved to reflect that change--it looks like I missed it in the original PR. I've made an issue at #170 if you have time to provide feedback and or submit a PR to address it.

**Comment by ticoombs** [comment]
These are not exotic installs but regular installs which we have no control over. As @RedKrieg also surmised we were never using host_vars correctly before and always imported the various variables that we needed. The folder "host_vars" was never used for the hosts. 

Forcing our ansible code to be on a single-homed host also reduces the flexibility of the code. Sure at the moment we are non-HA, but with the changes pictrs is making, we could easily be HA after that (assuming people don't use our postgres and use a hosted db service which others already do). While there isn't a plan set forth it is worth having it in the back of the mind. 

I like @sanatsathaye 's idea on using group vars. To build on that instead of `lemmy` I would like to have it as `{{ domain }}`. (A required manual change that people need to do as part of the `cp example/vars.yml group_vars/{{ domain }}/vars.yml`.

That would:
- make it easier for people to deploy to multiple domains (add all the servers to a new section in the inventory file).
- allow for logical segmentation of our various variables (per domain as a folder)
- allow for people to deploy to many servers (in the future)

---

### So I propose a 3 step solution:

1. Quickly fix all current ansible solution is to (as OP said) add:

> I already have a fix for this in my local machine:
```
vars_files:
    - inventory/host_vars/{{ domain }}/vars.yml
```

This ensures that we no longer break existing ansible installs and people can get back to doing what they do best. 

2. Fix our documentation, and create new version tags. 

We also need to update the documentation and possibly at this point in time start versioning our pushes to main. I suggest making the previous commit (https://github.com/LemmyNet/lemmy-ansible/commit/31631d2616de68f4398f976b6a569f68a02bdd9f) v1.1.0 
We then update the documentation to always show the latest stable and anything that is not backwards compatible we increase the major release version. (Following semver.org)

We need to start versioning to ensure we don't break peoples ci/cd pipelines. 
This will allow us to merge to main without having to worry about creating breaking changes or worry about creating hotfixes. 

3. Migrate from `host_vars` to `group_vars` for allowing future proofing (and the possibility of multi-server deployments)

host_vars are fine but group_vars is 👌 
[drake-meme hostvars vs group_vars](https://i.imgflip.com/7z2lwg.jpg)

This can be scheduled as our (lemmy-ansible) next major release with notes on upgrading. Also as it currently stands we can easily backport the "version" fixes. 

`@dessalines` and `@Nutomic` have more than enough on their plates and is most likely the reason they added us to the lemmy-ansible repo. 

----

I know I've gone slightly off topic here but it seems as good as any place.

**Comment by sanatsathaye** [comment]
+1 on the versioning of this installation guide, along with a documented changelog. These scripts have changed a lot in the past month and it would be quite problematic for people using this solution to upgrade existing installs if they're not made aware of the exact changes. Without that most would simply use a `git pull` and expect this to work every time, and it wouldn't be their fault.

**Comment by dessalines** [comment]
Yep I'd very much appreciate if someone could PR `Upgrading` subsections.

**Comment by codyro** [comment]
I'm going to close this in favor of #171 which was created from the discussion above.
