### ISSUE TITLE
Add PICTRS__API_KEY

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ansible#53]
Necessary to make admin purge of images work. Needs to be set as pictrs env var in docker-compose.yml, and in lemmy config.

Btw. this also needs to be added to instructions for manual installation.

**Comment by Djones4822** [comment]
This seems to have been added... except, shouldn't this be `PICTRS__SERVER__API_KEY`? 

```
The following endpoints are protected by an API key via the X-Api-Token header, and are disabled unless the --api-key option is passed to the binary or the PICTRS__SERVER__API_KEY environment variable is set.
```

**Comment by codyro** [comment]
Looks like this is added [here](https://github.com/LemmyNet/lemmy-ansible/blob/a4af56583916ea5073c8a3aebe99a0f59ef09e15/templates/docker-compose.yml#L59) and re-uses the postgresql password. 

This issue is tangentially related to #109. Let's consider not hard-coding the `PICTRS__SERVER__API_KEY`  environmental variable and have it defined alongside the other environmental variables (EX, https://github.com/LemmyNet/lemmy-ansible/issues/109#issuecomment-1629652836). This has the added benefit of making it easier for individuals to adjust the pict-rs behavior without modifying the playbook(s) directly.

I have a PR for #109 which I'll add this to and reference it.
