### ISSUE TITLE
Include installation of cron

### ISSUE THREAD

**Issue by freeskier93** [LemmyNet/lemmy-ansible#83]
Some minimal images don't have cron installed and I needed to manually install it.

**Comment by freeskier93** [comment]
This ansible deployment creates a cronjob for certbot renewal.

**Comment by codyro** [comment]
Sorry, you are correct! However `cron` is packaged in all target distributions (Debian 10,11,12/Ubuntu 22.04 LTS+) . Stripped down Docker images may not have `cron` installed, however it will likely fail in numerous sections of the playbook due to missing packages/utilities.

What Docker image are you attempting to run this playbook against? I'll take a peak, and assuming it's sane, I'll make a branch for you that should run cleanly :).

**Comment by freeskier93** [comment]
It was when I was testing on an Azure VM, I'm pretty sure it was Ubuntu Minimal 22.04 LTS that I had to manually install cron. That was a while ago though so I might be misremembering, currently running Lemmy on a different VPS with a regular Ubuntu image that did have cron installed.

**Comment by codyro** [comment]
It looks like this should also include the `cron` package. Since this is no longer an issue for you and I can't replicate it, I'll close it. If you run into it again, please feel free to re-open it :).
